steps:
  - command:
    - 'make ci_test'
    label: ':hammer: Tests'
    agents:
    - "queue=default"
  - command:
    - 'make ci_build'
    label: ':golang: Build'
    agents:
    - "queue=default"
  - command:
    - 'make ci_lint'
    label: ':golang::mag: Lint'
    agents:
    - "queue=default"
